language: python
sudo: false
python:
    - "3.6"
env:
    - POSTIX_STATIC_ROOT=`pwd`/src/static.dist
install:
    - pip install -U pip wheel setuptools codecov
    - pip install -r src/requirements.txt
script:
    - cd src
    - flake8 .
    - isort -rc -c .
    - python manage.py check
    - coverage run -m py.test tests && codecov
cache:
    directories:
        - $HOME/.cache/pip
